### PR TITLE
Fix /api/v1/*/wrong-uuid to return 404

### PR DESCRIPTION
**Pull request by karenc**
What happened when a request asks for `PATCH /api/v1/users/wrong-uuid`:

1. Did not match the route `/api/v1/users/<uuid:user_guid>`
   (`app.modules.users.resources.UserByID`) because "wrong-uuid" is not
   a valid uuid
2. Matched the route `/<path:path>`
   (`app.modules.frontend.views_frontend.home`) but this route only
   accepts "GET" as the method
3. Returned 405 Method Not Allowed

This is incorrect as it looks like the user exists but "PATCH" is not
allowed.  The code path taken is also probably not what we expected.

In this patch, I decided to split the routes `/` and `/<path:path>` into
`app.modules.frontend.views_frontend.home` and
`app.modules.frontend.catchall` so that it's more clear what those
routes are meant to return.

`/` is only meant to return "index.html".

`/<path:path>` now accepts all methods `GET`, `POST`, `PUT`, `DELETE`,
`HEAD`, `OPTIONS`, `PATCH`.  For `GET`, it will return something from
the static folder, for all other methods, it returns "not found".

Now `PATCH /api/v1/users/wrong-uuid` becomes:

1. Does not match the route `/api/v1/users/<uuid:user_guid>`
2. Matches the route `/<path:path>`
3. Returns 404 Not Found

**Pull Request Checklist**
- [x] Ensure that the PR is properly formatted
  - Example: All lint checks are passing
- [x] Ensure that the PR is properly rebased
  - Example: The PR is rebased on `develop` (commit: `<insert develop commit hash>`)
- [x] Ensure that the PR uses a consolidated database migration
  - Example: One database migration is proposed (revision `<insert develop revision>` -> `<insert new revision>`)
- [x] Ensure that the PR is properly tested
  - Example: All automated tests are passing
- [x] Ensure that the PR is properly covered
  - Example: The percentage of the code covered by tests has not decreased
- [x] Ensure that the PR is properly sanitized
  - Example: No sensitive data or large content was added to this PR
- [ ] Ensure that the PR is properly reviewed

### CODE REVIEW

**Comment by naknomum** [comment]
nice catch on this.  btw, i just confirmed, this seems to be a similar problem with **GET** and probably more.  that is to say, if a _non-UUID_ is passed it is redirected to the home page, e.g. `GET /api/v1/any-class/not-a-uuid` .. but if you do happen to select a _valid uuid_ (but one which does not exist in db) you get a 404 as expected.

probably this fix should be generalized to let these make more sense too.

**Comment by karenc** [comment]
@naknomum although the title of the PR and the tests are not generalized, the fix itself is. Maybe I can add a few more tests and change the title 🙂

**Comment by karenc** [comment]
@naknomum I added more tests!

**Comment by colinwkingen** [comment]
LGTM, great fix.

**Review by bluemellophone — COMMENTED** [review]
Looks good, requested double check for 404 handling with front-end

**Comment by karenc** [comment]
The tests I added:

```diff
diff --git a/tests/modules/frontend/test_views_frontend.py b/tests/modules/frontend/test_views_frontend.py
new file mode 100644                         
index 0000000..1bfd9ed                       
--- /dev/null                                
+++ b/tests/modules/frontend/test_views_frontend.py
@@ -0,0 +1,14 @@                             
+# -*- coding: utf-8 -*-                     
+def test_home(flask_app_client):            
+    response = flask_app_client.get('/')    
+    assert response.status_code == 200      
+                                            
+                                            
+def test_catchall_static_file(flask_app_client):
+    response = flask_app_client.get('/index.html')
+    assert response.status_code == 200      
+                                            
+                                            
+def test_catchall_not_found(flask_app_client):
+    response = flask_app_client.get('/asdf')
+    assert response.status_code == 404      
```

**Review by bluemellophone — APPROVED** [review]
LGTM

**Pull request merged**
