### PR TITLE
Add workflow to allow rebasing by keyword comment on a PR

### PR DESCRIPTION
**Pull request by mmulich**
## Pull Request Overview

The use of `/rebase` in a newly created comment will rebase the PR for
the developer.

---

**Review Notes**

Hopefully look at the comments of this PR to see that it worked?

**Pull Request Checklist**
- [X] Ensure that the PR is properly formatted
  - Example: All lint checks are passing
- [X] Ensure that the PR is properly rebased
  - Example: The PR is rebased on `develop` (commit: `<insert develop commit hash>`)
- [X] Ensure that the PR uses a consolidated database migration
  - Example: One database migration is proposed (revision `<insert develop revision>` -> `<insert new revision>`)
- [X] Ensure that the PR is properly tested
  - Example: All automated tests are passing
- [X] Ensure that the PR is properly sanitized
  - Example: No sensitive data or large content was added to this PR
- [x] Ensure that the PR is properly reviewed

### CODE REVIEW

**Comment by mmulich** [comment]
I can't seem to test it in this PR... IDK, sometimes there are edges to GitHub Actions that are very difficult to test prior to them landing in the upstream branch.

I suspect GitHub doesn't let the new workflow proposed in this PR run on this PR for security reasons. However searching for information about that is rather difficult, because all the terms for such a search are fairly generic.

**Comment by mmulich** [comment]
If the documentation at https://github.com/cirrus-actions/rebase is correct this should work.

**Comment by bluemellophone** [comment]
This is very neat and very handy.  I look forward to when this is ready.

**Review by karenc — APPROVED** [review]
I tested this using a forked repo and it seems that `github.event.comment.author_association == 'MEMBER'` doesn't work for me.  It could be that I'm not an organization so that check is failing.

Screenshot_2021-03-16  skull Test rebase workflow by karenc · Pull Request #1 · karenc houston

^ You can see github-action bot force pushing to the PR

I also checked that this github action only works when it's on `master`.

**Comment by karenc** [comment]
If github detects there's a conflict that needs to be resolved manually then the github action doesn't do anything.

**Comment by karenc** [comment]
@colinwkingen Ready to be merged but it needs to be in `master` before we can use `/rebase` to automatically rebase a PR.

**Pull request merged**
