### PR TITLE
Add test for deleting sighting deletes assets and asset groups

### PR DESCRIPTION
**Pull request by karenc**
Once a sighting is deleted, all the assets and asset groups should be
deleted.

### CODE REVIEW

**Review by naknomum — APPROVED** [review]
looks good

**Comment by karenc** [comment]
@naknomum In DEX-220 deletion of asset should check containing submission for emptiness, you said:

> `asset.delete()` needs to check if the asset in question (being deleted) is the last asset  in that submission.  if the submission will be empty, it too must be deleted.

`asset.delete()` doesn’t delete the asset group but `asset.delete_cascade()` does.  Is this ok or do we want to do something else?

**Comment by naknomum** [comment]
> @naknomum In DEX-220 deletion of asset should check containing submission for emptiness, you said:
> 
> > `asset.delete()` needs to check if the asset in question (being deleted) is the last asset  in that submission.  if the submission will be empty, it too must be deleted.
> 
> `asset.delete()` doesn’t delete the asset group but `asset.delete_cascade()` does. Is this ok or do we want to do something else?

i dont remember why, but i felt there was a need to be able to explicitly do one or the other.   but it seems like that may be a bad idea, i guess.  why would we want to delete (including db instance) an asset, without doing the check for empty asset_group?  i cant come up with a reason right now.  :)

**Comment by karenc** [comment]
@naknomum `delete_cascade` was added in #83 and the specific commit was a425d4d0.  There's no clear explanations as to why in the commit message and PR but it looks like `delete_cascade` is called when a sighting is deleted, the code doesn't delete asset's annotations and sightings and may be it's trying to avoid a loop because sighting is deleting an asset and then asset is also deleting sightings... ??

https://github.com/WildMeOrg/houston/blob/06628bb6d8caf2b66bd024895bfd113a8e880e3a/app/modules/assets/models.py#L199-L205


https://github.com/WildMeOrg/houston/blob/06628bb6d8caf2b66bd024895bfd113a8e880e3a/app/modules/assets/models.py#L207-L212


When looking at this code I also wonder if the `delete()` code is actually correct....  `asset.delete()` is called when an asset group is deleted.  Does it make sense when the asset is deleted that all its sightings are also deleted...? :thinking: Don't sightings have more than one asset?  Do sightings also need a `justify_existence` instead of just delete?

And then there's also the question of whether it's correct that `delete_cascade` doesn't delete annotations... 

https://github.com/WildMeOrg/houston/blob/06628bb6d8caf2b66bd024895bfd113a8e880e3a/app/modules/asset_groups/models.py#L1123-L1134

https://github.com/WildMeOrg/houston/blob/06628bb6d8caf2b66bd024895bfd113a8e880e3a/app/modules/sightings/models.py#L140-L152

It's all really complicated... In the sightings models.py, there's no mention of asset groups.  But asset groups are definitely linked to sightings....

**Comment by hwindsor** [comment]
Follow on from what @karenc and @naknomum have said, the thing to recall is that asset deletion does not result in the deletion of the sighting. Only the linkage between the sighting and the asset which is the SightingAssets object. The backref name is possibly wrong as it's causing confusion. Possibly both of them should change in the SightingAssets object:
assets -> sightingAssets
sightinigs -> assetSightings  
That would probably reduce confusion

**Pull request merged**
