### PR TITLE
Small users changes for dex 382

### PR DESCRIPTION
**Pull request by drewblount**

### CODE REVIEW

**Comment by colinwkingen** [comment]
Getting a couple test failures here. Perhaps a database migration needs to be included?

**Comment by karenc** [comment]
**Note:** If you have done `/rebase` on github, your local branch is going to
be outdated.  You should not "merge" it.  Either get rid of your local branch
and checkout again or do `git reset --hard origin/users-dex-382` to sync up.

1. Check out the branch:

   ```
   git checkout users-dex-382
   ```

2. Look at the commits in the branch:

   ```
   $ git log --graph --oneline --decorate origin/main..
   *   1447c928 (HEAD -> users-dex-382, origin/users-dex-382) Merge branch 'users-dex-382' of https://github.com/WildMeOrg/houston into users-dex-382
   |\
   | * 0b886733 linting fixes
   | * de0fcdd1 small commit that adds pagination to the user/sightings api for purposes of populating a summary table. We may choose to further pare down the sightings data to make this more lightweight
   | * 4fbae035 Updates field defaults to empty string rather than null
   * 1a4cc3a4 linting fixes
   * 0527b7e5 small commit that adds pagination to the user/sightings api for purposes of populating a summary table. We may choose to further pare down the sightings data to make this more lightweight
   * 608b2048 Updates field defaults to empty string rather than null
   ```

   **Note:** We have the same 3 commits twice because of this "Merge branch 'users-dex-382'" commit

3. Look at the diff of each commit:

   ```
   git show origin/main..
   ```

   **Note:** The 3 commits have exactly the same diff so we only need to keep one set of the commits.

4. Use interactive rebase to pick the commits:

   ```
   git rebase -i origin/main
   ```

   Interactive rebase shows this in my editor:

   ```
   pick 608b2048 Updates field defaults to empty string rather than null
   pick 0527b7e5 small commit that adds pagination to the user/sightings api for purposes of populating a summary table. We may choose to further pare down the sightings data to make this more lightweight
   pick 1a4cc3a4 linting fixes
   pick 4fbae035 Updates field defaults to empty string rather than null
   pick de0fcdd1 small commit that adds pagination to the user/sightings api for purposes of populating a summary table. We may choose to further pare down the sightings data to make this more lightweight
   pick 0b886733 linting fixes
   ```

   Let's pick the first set of the commits, what we want is:

   ```
   pick 608b2048 Updates field defaults to empty string rather than null
   pick 0527b7e5 small commit that adds pagination to the user/sightings api for purposes of populating a summary table. We may choose to further pare down the sightings data to make this more lightweight
   pick 1a4cc3a4 linting fixes
   drop 4fbae035 Updates field defaults to empty string rather than null
   drop de0fcdd1 small commit that adds pagination to the user/sightings api for purposes of populating a summary table. We may choose to further pare down the sightings data to make this more lightweight
   drop 0b886733 linting fixes
   ```

   **Note:** drop the last 3 commits.

   Save and quit the editor.

5. Check how the commits look again:

   ```
   $ git log --graph --oneline --decorate origin/main..
   * 3ce40f0f (HEAD -> users-dex-382) linting fixes
   * e4aaf388 small commit that adds pagination to the user/sightings api for purposes of populating a summary table. We may choose to further pare down the sightings data to make this more lightweight
   * 9084eecc Updates field defaults to empty string rather than null
   ```

   ```
   $ git log --graph --oneline --decorate HEAD origin/main
   * 3ce40f0f (HEAD -> users-dex-382) linting fixes
   * e4aaf388 small commit that adds pagination to the user/sightings api for purposes of populating a summary table. We may choose to further pare down the sightings data to make this more lightweight
   * 9084eecc Updates field defaults to empty string rather than null
   *   5b8d993a (origin/main) Merge pull request #278 from WildMeOrg/dex-422-gitlab-sshkey
   ```

6. Check the diff from the original branch on github to make sure we didn't accidentally remove changes:

   ```
   $ git diff origin/users-dex-382.. app/modules/users/models.py app/modules/users/resources.py
   ```

   **Note:** We only want to check `app/modules/users/models.py` and
   `app/modules/users/resources.py` because those are the only files changed in
   this pull request.

7. Run tests and fix all the failed tests:

   ```
   docker-compose exec houston pytest -s -x
   ```

   **Note:** `-s` to print stdout and `-x` to stop at the first failure.

   **Note:** Commit the changes using:

   ```
   git commit --fixup e4aaf388 app/modules/users/resources.py
   git commit --fixup 9084eecc tests/modules/users/resources/test_signup.py
   ```

8. Now the commits look like:

   ```
   $ git log --graph --oneline --decorate origin/main..
   * ac87a801 (HEAD -> users-dex-382) fixup! Updates field defaults to empty string rather than null
   * 33064537 fixup! small commit that adds pagination to the user/sightings api for purposes of populating a summary table. We may choose to further pare down the sightings data to make this more lightweight
   * 3ce40f0f linting fixes
   * e4aaf388 small commit that adds pagination to the user/sightings api for purposes of populating a summary table. We may choose to further pare down the sightings data to make this more lightweight
   * 9084eecc Updates field defaults to empty string rather than null
   ```

9. Squash the fixup commits and the "linting fixes" commit:

   ```
   git rebase -i --autosquash origin/main
   ```

   ```
   pick 9084eecc Updates field defaults to empty string rather than null
   fixup ac87a801 fixup! Updates field defaults to empty string rather than null
   pick e4aaf388 small commit that adds pagination to the user/sightings api for purposes of populating a summary table. We may choose to further pare down the sightings data to make this more lightweight
   fixup 33064537 fixup! small commit that adds pagination to the user/sightings api for purposes of populating a summary table. We may choose to further pare down the sightings data to make this more lightweight
   pick 3ce40f0f linting fixes
   ```

   **Note:** `git rebase --autosquash` automatically move the fixup commits to the right place

   Change the last line from "pick" to "fixup" so it'll get squashed into e4aaf388.

10. Check the commits again and there should only be 2 commits:

    ```
    $ git log --graph --oneline --decorate origin/main..
    * 4d635c83 (HEAD -> users-dex-382) small commit that adds pagination to the user/sightings api for purposes of populating a summary table. We may choose to further pare down the sightings data to make this more lightweight
    * 5f2b3024 Updates field defaults to empty string rather than null
    ```

11. Force push to github:

    ```
    git push -f origin HEAD
    ```
<details>
<summary>The changes I made to fix the tests:</summary>

```diff
commit 3306453745e46b0cdfdc62c9b1c35da7b4f4d43a
Author: karen chan <karen@karen-chan.com>
Date:   Tue Aug 24 10:22:57 2021 +0100

    fixup! small commit that adds pagination to the user/sightings api for purposes of populating a summary table. We may choose to further pare down the sightings data to make this more lightweight

diff --git a/app/modules/users/resources.py b/app/modules/users/resources.py
index 8cd67a23..1cdfa097 100644
--- a/app/modules/users/resources.py
+++ b/app/modules/users/resources.py
@@ -322,7 +322,7 @@ class UserSightings(Resource):
         },
     )
     @api.parameters(PaginationParameters())
-    def get(self, user, args):
+    def get(self, args, user):
         """
         Get Sightings for user with EDM metadata
         """
```

```diff
commit ac87a801d9ac3dc8a9984ca419372e55beeda011
Author: karen chan <karen@karen-chan.com>
Date:   Tue Aug 24 10:24:16 2021 +0100

    fixup! Updates field defaults to empty string rather than null

diff --git a/tests/modules/users/resources/test_signup.py b/tests/modules/users/resources/test_signup.py
index 45c8b00a..fa9de336 100644
--- a/tests/modules/users/resources/test_signup.py
+++ b/tests/modules/users/resources/test_signup.py
@@ -247,10 +247,10 @@ def test_new_user_creation_roles_admin(flask_app_client, admin_user, db):
     assert response.content_type == 'application/json'
     user_guid = response.json['guid']
     assert response.json == {
-        'affiliation': None,
+        'affiliation': '',
         'created': response.json['created'],
         'email': 'user1@localhost',
-        'forum_id': None,
+        'forum_id': '',
         'full_name': '',
         'guid': user_guid,
         'in_alpha': True,
@@ -263,7 +263,7 @@ def test_new_user_creation_roles_admin(flask_app_client, admin_user, db):
         'is_researcher': True,
         'is_staff': False,
         'is_user_manager': False,
-        'location': None,
+        'location': '',
         'profile_fileupload': None,
         'updated': response.json['updated'],
         'viewed': response.json['viewed'],
```

</details>

**Review by colinwkingen — APPROVED** [review]
LGTM

**Pull request merged**
