### PR TITLE
Frontend & Swagger UI build scripting

### PR DESCRIPTION
**Pull request by mmulich**
## Pull Request Overview

- Continuation of #125 
- Fixes the frontend build (mostly by updating the submodule ref)
- Frontend build script now gives useful remediation steps on error
- Fixes the build scripts so that they may be sourced (e.g. `source ./scripts/build.frontend.sh && build`)
- Builds the frontend & swagger-ui into the image (note, followup changes will improve upon this)

---

**Review Notes**

This is a direction setting changeset... Most of the changes were previously accepted in #125. The major difference is the foundational bits that fix the build script and allow them to be used within the image instructions.

The followup direction of these changes is towards allowing the user to override the Houston code without paving over the pre-built frontend or swagger-ui already in the container image.

**Pull Request Checklist**
- [X] Ensure that the PR is properly formatted
  - Example: All lint checks are passing
- [X] Ensure that the PR is properly rebased
  - Example: The PR is rebased on `develop` (commit: `<insert develop commit hash>`)
- [X] Ensure that the PR uses a consolidated database migration
  - Example: One database migration is proposed (revision `<insert develop revision>` -> `<insert new revision>`)
- [X] Ensure that the PR is properly tested
  - Example: All automated tests are passing
- [X] Ensure that the PR is properly covered
  - Example: The percentage of the code covered by tests has not decreased
- [X] Ensure that the PR is properly sanitized
  - Example: No sensitive data or large content was added to this PR

### CODE REVIEW

**Review by brmscheiner — COMMENTED** [review]
So I checked out this branch and modified `docker-compose.yml` to use my local frontend instead of the houston `_frontend` folder.  Then I ran `docker-compose build` followed by `docker-compose up -d`. Looks like the Houston container quit with a gitlab-related error:

```
houston_1       | 2021-04-20 15:29:16,580 [INFO] [app] Using app.config 'docker_local_config.LocalConfig'
houston_1       | 2021-04-20 15:29:17,894 [INFO] [alembic.runtime.migration] Context impl PostgresqlImpl.
houston_1       | 2021-04-20 15:29:17,894 [INFO] [alembic.runtime.migration] Will assume transactional DDL.
houston_1       | 2021-04-20 15:29:18,082 [INFO] [alembic.runtime.migration] Context impl PostgresqlImpl.
houston_1       | 2021-04-20 15:29:18,082 [INFO] [alembic.runtime.migration] Will assume transactional DDL.
houston_1       | Creating AssetGroup path: '/data/var/asset_group'
houston_1       | 62964b09ea91 (head)
houston_1       | /docker-entrypoint.sh: ignoring /docker-entrypoint-init.d/_set_up_gitlab.py
houston_1       | 
houston_1       | /docker-entrypoint.sh: running /docker-entrypoint-init.d/set_up_gitlab.sh
houston_1       | Complete the wizard setup for gitlab & create a admin personal access token (PAT)
houston_1       | Traceback (most recent call last):
houston_1       |   File "/usr/local/lib/python3.9/site-packages/lxml/html/__init__.py", line 408, in get_element_by_id
houston_1       |     return _id_xpath(self, id=id)[0]
houston_1       | IndexError: list index out of range
houston_1       | 
houston_1       | During handling of the above exception, another exception occurred:
houston_1       | 
houston_1       | Traceback (most recent call last):
houston_1       |   File "/docker-entrypoint-init.d/_set_up_gitlab.py", line 25, in parse_form
houston_1       |     form = html.get_element_by_id(form_id)
houston_1       |   File "/usr/local/lib/python3.9/site-packages/lxml/html/__init__.py", line 413, in get_element_by_id
houston_1       |     raise KeyError(id)
houston_1       | KeyError: 'new_personal_access_token'
houston_1       | 
houston_1       | During handling of the above exception, another exception occurred:
houston_1       | 
houston_1       | Traceback (most recent call last):
houston_1       |   File "/docker-entrypoint-init.d/_set_up_gitlab.py", line 89, in <module>
houston_1       |     main()
houston_1       |   File "/docker-entrypoint-init.d/_set_up_gitlab.py", line 76, in main
houston_1       |     form_data, action = parse_form(session, url, 'new_personal_access_token')
houston_1       |   File "/docker-entrypoint-init.d/_set_up_gitlab.py", line 27, in parse_form
houston_1       |     raise RuntimeError(f'form not found in {resp} for {url}')
houston_1       | RuntimeError: form not found in <Response [200]> for http://gitlab/-/profile/personal_access_tokens
codex_houston_1 exited with code 1
```

**Comment by mmulich** [comment]
@brmscheiner I'm not real sure what that's about. I didn't change anything around that procedure. Best I can say is try again. 😬

**Review by colinwkingen — APPROVED** [review]
LGTM

**Pull request merged**
