### PR TITLE
DEX-889 Remove sqlite implementation

### PR DESCRIPTION
**Pull request by mmulich**
## Pull Request Overview

- Removes sqlite from the testing workflow
- Remove the sqlite implementation specifics
- Implements error when SQLALCHEMY_DATABASE_URI is blank or undefined

---

It should work as it has in the past just without sqlite.

### CODE REVIEW

**Comment by mmulich** [comment]
Note, the "Required" tests that say status "Expected" are not going to run because I'd changed the test names. The database URI string is no longer a part of the test name. Instead it'll be `test (<python-version>, <app-context>)`.

**Comment by bluemellophone** [comment]
I reviewed this PR and noticed that the migrations weren't updated.  I've searched for different references for SQLite and have removed them as well.

**Comment by colinwkingen** [comment]
Any idea what is up with the postgres tests not making it out of expected?

**Review by colinwkingen — APPROVED** [review]
LGTM

**Pull request merged**
