### PR TITLE
Single container image for a multi-context houston application

### PR DESCRIPTION
**Pull request by mmulich**
## Houston for different contexts but without separation

Moves towards allowing for an application context (either `codex` or `mws`). This enables the code, tooling infrastructure and supporting scripts to share the same space. One can now flip between the application contexts using the `HOUSTON_APP_CONTEXT` environment variable.

The previous concept of `FLASK_CONFIG`, which defined the environment under which the application ran, has been removed in favor of using Flask's built-in `FLASK_ENV`. This gives us the built-in behaviors that Flask associates with some environments (e.g. `development` automatically enables debug mode and template reloading). 

The `HOUSTON_APP_CONTEXT` is now a required setting. It's not something the developer using the docker setup needs to think about, but in the event that it is forgotten, a specific error message is raised at startup.

The configuration has been put into a package with two entry-points for usage. The main entry-point is `configure_app`, which when given a Flask instance will associate the configuration with the application. The other entry-point is `get_preliminary_config`, which allows the developer to access the preliminary configuration object prior to it being associated with the Flask application. This later method is necessary for various bits of the application that require information before the Flask instance is available.

## Single image to serve all contexts

The container image has been changed back to `wildme/houston`. We're able to do this because we can switch the application context by changing the `HOUSTON_APP_CONTEXT` environment variable, thus allowing us to have both apps in the same container.

## New vector in the testing matrix

The contexts have been made a vector in the testing matrix. As a result, there has been a reduction in the duplication of testing instructions.

Where necessary (e.g. `run_tasks_for_coverage.sh`) test conditions have been put in for specific application contexts. This is done by checking the value of `HOUSTON_APP_CONTEXT`, which is now a required setting.

Side note, this change has reduced the test run time by 4-10mins.

Also note, that the required github checks will need to be updated, because job names now include the context.

### CODE REVIEW

**Comment by mmulich** [comment]
T'is ready for review. Tests were passing prior to the ACM startup problem (mentioned in slack).

**Review by colinwkingen — APPROVED** [review]
LGTM

**Pull request merged**
