### PR TITLE
732 notif collab resolve

### PR DESCRIPTION
**Pull request by drewblount**
The prior PR for this branch left out the case of a collaboration request being denied, where the request notif should be resolved. That is addressed here. The code changes fall into three categories:

1. Adding a new notification type called `NotificationType.collab_denied`, including email templates. However, it is configured in `Notification.NOTIFICATION_DEFAULTS` to send notifications *neither* by rest api nor email, meaning this notif is by default _never_ sent to a user. We've decided in discussions not to send notifications on a collab denial, but it is convenient to have this as a proper notification type because then the request `is_resolved` logic is consistent across all events. Additionally, we or admin users may choose to send these notifs in the future by changing these config fields.

2. Adding a test for denying a collaboration request, which was not previously covered. This new test in `tests/modules/collaborations/resources/test_collaboration_patch.py` also checks for proper notification resolution.

3. Many of the diffs here are from renaming instances of collab.DECLINED to collab.DENIED. We were inconsistent in the usage of those two terms; I have standardized on DENIED since that is the usual counterpart to 'approved'.

### CODE REVIEW

**Comment by drewblount** [comment]
\rebase

**Review by colinwkingen — APPROVED** [review]
LGTM

**Review by hwindsor — COMMENTED** [review]
LGTM, only just spotted this

**Pull request merged**
