### PR TITLE
Move non-critical path testing to nightly schedule

### PR DESCRIPTION
**Pull request by mmulich**
## Pull Request Overview

This changes our PR tests to run critical path testing that focuses on the following environments:
- Python 3.9 with SQLite
- Python 3.9 with Postgres

The goal is to test the critical path--that which we deploy with--for change acceptance.
The focus is on producing deployable code and a more responsive development workflow that concentrates on producing deployable code.

This moves the non-critical testing paths to the nightly scheduled workflow. We'll still be notified in the event that PR changes do cause problems on the mac or in other versions of python.

---

We're moving in this direction because _soon_ we'll be pulling in externally run and deployed services as services setup and local to these tests. For example, we'll be pulling in a local instance of EDM as a service running alongside the tests. This will mean that the developer can move to a new version of EDM without needing to bump the externally deployed service. Thus we're able to isolate the changes without effecting other developers in the process (enabling better parallel working).

---

**Review Notes**

Not much to review... just ensure all the CI bits are running through successfully.

The slack notification to the `#dev-houston` channel is working, I've tested it.

**Pull Request Checklist**
- [X] Ensure that the PR is properly formatted
  - Example: All lint checks are passing
- [X] Ensure that the PR is properly rebased
  - Example: The PR is rebased on `develop` (commit: `<insert develop commit hash>`)
- [X] Ensure that the PR uses a consolidated database migration
  - Example: One database migration is proposed (revision `<insert develop revision>` -> `<insert new revision>`)
- [X] Ensure that the PR is properly tested
  - Example: All automated tests are passing
- [X] Ensure that the PR is properly covered
  - Example: The percentage of the code covered by tests has not decreased
- [X] Ensure that the PR is properly sanitized
  - Example: No sensitive data or large content was added to this PR
- [x] Ensure that the PR is properly reviewed

### CODE REVIEW

**Review by karenc — APPROVED** [review]

**Comment by mmulich** [comment]
The seemingly random failures in the tests are associated with problems connecting to the wildme gitlab instance. As the PR description mentions, we're trying to move in the direction that would eliminate this problem by localizing the gitlab instance within the CI job run. I'll just keep rerunning until it's maybe successful.

**Comment by mmulich** [comment]
The "Required" checks will need to be adjusted for the PR to be merged. As noted in the description, I've reduced the PR tests to two tests. So our required checks would likely become:
- Docker / deploy
- Testing / lint
- Testing / test (3.9, postgresql://postgres:testing@localhost/postgres)
- Testing / test (3.9, sqlite://)

**Comment by mmulich** [comment]
Looks like everything is now passing... as mentioned before, just needs the "Required" checks changed to make this mergeable.

**Comment by mmulich** [comment]
Changes to the required checks can be made at https://github.com/WildMeOrg/houston/settings/branches

**Pull request merged**
