### PR TITLE
ia json restructuring

### PR DESCRIPTION
**Pull request by hwindsor**
## Pull Request Overview

- Restructure IA Json so that the _identifiers data is in blocks
- Change calling code so that it knows only which block(s) it is to use, not the individual fields that it needs to remove

---

### CODE REVIEW

**Review by drewblount — APPROVED** [review]
Looks good to me. This tidies up the format and the logic, making them more readable and scalable if we add fields later.

**Comment by colinwkingen** [comment]
@drewblount What to you think would be the best place to make a note of these required changes? I'm of a mind to approve and merge this in the meantime.

**Review by colinwkingen — APPROVED** [review]
LGTM

**Pull request merged**
