### PR TITLE
DEX-331 Users/me returns unprocessed sightings

### PR DESCRIPTION
**Pull request by hwindsor**
## Pull Request Overview

- Users/me API now returns a list of unprocessed sightings for the user to process

---

**REST API Updates**

A new example POST API is defined with its expected parameters, if needed to be specified for a thorough review

```
[GET] /api/v1/users/ma
{
    'sightings': ['uuid', 'uuid'],
}
```

### CODE REVIEW

**Comment by hwindsor** [comment]
Summat weird going on here, converting to draft until I sort it out

**Review by naknomum — APPROVED** [review]
looks good.

**Pull request merged**
