### PR TITLE
Updates to tus limits

### PR DESCRIPTION
**Pull request by karenc**
- DEX-1052 Increase TUS_MAX_FILES_PER_TRANSACTION to 20000

  The original, 5000, was too low.  We just want to include a limit that
  normal users won't hit.

- DEX-1052 Increase default MAX_CONTENT_LENGTH to 50MB

  This default is used in codex, in mws, it's still 100MB.  This limits
  the size of each uploaded file.

- Import HTTPStatus from built-in http module

  I checked the module we were importing from `flask_restx._http` and at
  the top of this file is:
  
  ```
  This file is backported from Python 3.5 http built-in module.
  ```
  
  Since we're using python 3.9, I think we can safely switch to the
  built-in `http` module.

- DEX-1052 Overwrite 413 error to be more user friendly

  When users upload files that exceed the MAX_CONTENT_LENGTH (50MB for
  codex), they will see this message when they click on the "?" next to
  "Upload failed":
  
  ```
  Upload failed
  
  Failed to upload 20190224_131607.jpg tus: unexpected response while
  uploading chunk, originated from request (method: PATCH, url:
  http://localhost/api/v1/tus/9fa47e65-b8b1-489c-bb79-69b1eeea16a9,
  response code: 413, response text: {
    "message": "The uploaded file has exceeded our limit of 50.0MB",
    "status": 413
  }
  , request id: n/a)
  ```
  
  The message they used to see:
  
  ```
  Upload failed
  
   Failed to upload Free-3.jpg tus: unexpected response while uploading chunk, originated from request (method: PATCH, url: http://localhost/api/v1/tus/aae6f115-017f-48e3-b94e-4b988e446cf5, response code: 413, response text: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
  <title>413 Request Entity Too Large</title>
  <h1>Request Entity Too Large</h1>
  <p>The data value transmitted exceeds the capacity limit.</p>
  , request id: n/a)
  ```

### CODE REVIEW

**Comment by karenc** [comment]
@bluemellophone I noticed that we clean up tus directories after 1 hour, which means if the user doesn't submit the sightings form within 1 hour, their files are deleted.  1 hour doesn't seem like a long time, would it be better to extend it to 24 hours?  This is how the error looks like if the user doesn't submit the sightings form within an hour:

Screenshot 2022-07-14 at 13-21-35 Report a Sighting • My test site

**Comment by bluemellophone** [comment]
Yes, I agree that 1 hour is likely too short.  It can be raised to 24 hours.

**Review by bluemellophone — APPROVED** [review]
LGTM

**Review by bluemellophone — APPROVED** [review]
Approved time bump

**Pull request merged**
