### PR TITLE
Dex 302 basic individual naming support.

### PR DESCRIPTION
**Pull request by colinwkingen**
This is just a test against the new EDM work for individual naming. 

The Individual names can be updated like any other field in a 'key': 'value' JSON format. 

Example: 

`[{"op":"add","path":"/names","value": "{ 'newestName': 'New Name' }" }]`

Add, remove and replace are supported. Incremental names, and multiple names for a single key are not yet supported. 

The JSON for a value is a little awkward. In testing I had to escape some characters. Open to suggestions on how to make it less so.

### CODE REVIEW

**Comment by naknomum** [comment]
this is a "i am not sure how it works even in old-world" question.   do we allow (need to allow?) for a "non-keyed" name, that is _without_ `newestName` in your example?  something like:  `op=add`, `path=/names`, `value=Charlie` .... that would set/add-to the default-or-whatever name?   just kinda curious.  if not, thats fine and the burden is on the caller to come up with using the right "key".

**Review by naknomum — APPROVED** [review]
looks good to me.  will try to scan the edm change too; but signing off over here in python-land.

**Comment by colinwkingen** [comment]
It would be pretty easy to add support for a non-keyed name if we need it. There's going to be at least one more naming PR where that could be included.

**Pull request merged**
