### PR TITLE
Add owner, location_ids and verbatim_localities to the sightings index

### PR DESCRIPTION
**Pull request by karenc**
```
    {
      "_index": "sightings",
      "_type": "_doc",
      "_id": "sighting_00006226-3f11-4711-bebe-c14faf1201d5",
      "_score": 1,
      "_source": {
        "id": "00006226-3f11-4711-bebe-c14faf1201d5",
        "point": "0.042395091740593,36.9557105308591",
        "location_ids": [
          "Ol Pejeta.East"
        ],
        "verbatim_localities": [
          "Zebra Plain"
        ],
        "datetime": "2020-01-17T10:36:00+03:00",
        "time_specificity": "time",
        "taxonomy": "Equus quagga",
        "comments": "None",
        "custom_fields": {
          "c54a17b8-9a58-4834-9947-641235ea9477": "Standing"
        },
        "owner": "1a750458-5d66-41ca-a3f4-aa27c52f21a8"
      }
    },
```

### CODE REVIEW

**Comment by karenc** [comment]
@naknomum Are there other location fields (or not location) I should include?

**Comment by naknomum** [comment]
> @naknomum Are there other location fields (or not location) I should include?

i believe you have the `decimalLatitude` (and Longitude) already on sighting, yes?  definitely `locationId` (which i think you already do on Encounters -- this comes from EDM), as well as `verbatimLocality` (from EDM also -- basically freetext users can add)

**Comment by karenc** [comment]
location_ids and verbatim_localities added.  See also WildMeOrg/gumby#10

**Comment by naknomum** [comment]
> location_ids and verbatim_localities added. See also [WildMeOrg/gumby#10](https://github.com/WildMeOrg/gumby/pull/10)

on each Sighting (really on each Occurrence in edm, but kinda same thing) there is _only one_ `locationId` and one `verbatimLocality`, so these should not be arrays.   note:  a Sighting may include 1+ Encounter -- and each _of these_ has their own `locationId` and `verbatimLocality`.  (so these can conceivably be thought of as lists of these values within a Sighting.)
note though that the properties on Sighting are separate.

also, i wonder if @brmscheiner might prefer the search terms to share the camel-case format of these (`locationId`) instead of the pythonic snake-case (`location_id`) etc.   i defer that question to him.

**Review by colinwkingen — APPROVED** [review]
LGTM

**Pull request merged**
