### PR TITLE
Statically built development targeted container

### PR DESCRIPTION
**Pull request by mmulich**
## Organize the docker ignores

The hope is that this will help us understand why an ignore was put in
place. Generally speaking we don't want personal exceptions to be in
the ignore list, because that would create a huge file. Though,
personal files shouldn't really be an issue, because no one should be
publishing the container from their local machine (CI does that for us).

## Remove clients directory

I don't think this is of use to us. The data within contains examples
without instruction rather than information useful to us in this project.

## Add a development build target to the container instructions

The logic to resolve developer dependencies (e.g. testing
dependencies) has been removed from the entrypoint script. This logic
is now moved into the `development` build target.

This change attempts to mitigate connection issues by ensuring the
developer can continue working in the absence of a good connection to
pypi. That is to say that the built container will no longer request
packages on first run or restart, but instead will have them built in.

This will however require the developer to re-build the image when
dependencies are added to the code, as opposed to them magically
getting resolved on a restart of the containerized service.

### CODE REVIEW

**Comment by mmulich** [comment]
I've pinged @hwindsor in slack for review.

**Comment by mmulich** [comment]
Ok, looks like a small issue... The `version.py` gets written on startup via this procedure. I'm going to put in a dummy file. Then put in an ignore rule to explicitly not allow changes to the file to be checked in unless forcibly done so.

**Review by hwindsor — APPROVED** [review]
LGTM (with the caveat that this means that I can see the changes, understand most of what they mean locally but not what they mean WRT the full system interaction but happy to take your word for it)

**Comment by mmulich** [comment]
Predates my changes that remove the PROJECT build argument.

**Pull request closed without merging**
