### PR TITLE
DEX-201 Create single db transaction for encounters patch API

### PR DESCRIPTION
**Pull request by karenc**
- Add example to show how transactions work

  The view code for `/api/v1/test-transactions/` is basically:
  
  ```
  (implicitly or explicitly) start db transaction:
      change full_name
      change locale
      start nested transaction:
          change website
      change email
  ```
  
  Check nothing is updated if locale is too long.
  
  Check nothing is updated if website is too long.
  
  Check everything is updated if everything goes through.

- Create single db transaction for encounters patch API

  This means if anything fails during the encounters patch API everything
  written to the database will be reverted.

# Review Notes

> What do people think about implicitly starting a db transaction in the before_request hook and committing in the after_request hook?
>
> This way we can definitely avoid accidental changes to the database.  We sometimes call functions from our views and we may miss that the function actually commits something to the database.  By having an implicit database transaction around request, we can be sure everything that happened within the request is reverted.

Jason raised concerns about locking the database for the whole of the request.  We can possibly look into isolation level but we'll leave it for now

> I haven't done the change yet but I think it's ok to change all the `db.session.begin()` to `db.session.begin(subtransactions=True)` because it seems to work whether or not there's already a transaction.

We are only adding `subtransactions=True` where necessary

---

**Pull Request Checklist**
- [x] Ensure that the PR is properly formatted
  - Example: All lint checks are passing
- [x] Ensure that the PR is properly rebased
  - Example: The PR is rebased on `develop` (commit: `<insert develop commit hash>`)
- [x] Ensure that the PR uses a consolidated database migration
  - Example: One database migration is proposed (revision `<insert develop revision>` -> `<insert new revision>`)
- [x] Ensure that the PR is properly tested
  - Example: All automated tests are passing
- [x] Ensure that the PR is properly sanitized
  - Example: No sensitive data or large content was added to this PR
- [ ] Ensure that the PR is properly reviewed

### CODE REVIEW

**Comment by colinwkingen** [comment]
`This way we can definitely avoid accidental changes to the database. We sometimes call functions from our views and we may miss that the function actually commits something to the database. By having an implicit database transaction around request, we can be sure everything that happened within the request is reverted.`

So the idea is that there is a parent transaction in the request that we can commit or roll back as appropriate, and that decision will apply to subtransactions that happen further down in the code?

This seems like a good idea to me.

**Review by hwindsor — APPROVED** [review]
All seems fine to me,
Don't know enough to fully get the consequences but as you've tested it and shown it gets around the issues.
That's all that I can see required

**Comment by bluemellophone** [comment]
> `This way we can definitely avoid accidental changes to the database. We sometimes call functions from our views and we may miss that the function actually commits something to the database. By having an implicit database transaction around request, we can be sure everything that happened within the request is reverted.`
> 
> So the idea is that there is a parent transaction in the request that we can commit or roll back as appropriate, and that decision will apply to subtransactions that happen further down in the code?
> 
> This seems like a good idea to me.

The problem wish this plan is that it keeps a very long database transaction open for no reason

**Comment by bluemellophone** [comment]
I have added a new commit that reduces the DB transaction session blocks to as small as possible.  This may end up breaking a few tests (there is one delete I'm concerned about), but otherwise this PR looks very good.

**Review by bluemellophone — DISMISSED** [review]
LGTM

**Review by bluemellophone — DISMISSED** [review]
LGTM

**Review by bluemellophone — APPROVED** [review]
LGTM, tests were failing due to bag GitLab submissions, now fixed.

**Review by bluemellophone — APPROVED** [review]
Merged

**Pull request merged**
