### PR TITLE
Dex 460 more fields for individual API

### PR DESCRIPTION
**Pull request by colinwkingen**
Small PR to add a few fields to the Individual API response per @brmscheiner 's request. New response should look a little something like this: 

```javascript
{
	'comments': 'None',
	'encounters': [{
		'individual': {
			'names': {
				'nickname': 'Meatloaf',
				'defaultName': 'Micheal Aday'
			},
			'id': 'fc35b212-3d96-4071-b290-6ab22df4ec0b'
		},
		'customFields': {},
		'locationId': 'Saturn',
		'decimalLongitude': '25.9999',
		'decimalLatitude': '25.9999',
		'verbatimLocality': 'Saturn',
		'id': 'f9aabbd7-56c6-4a68-a097-46fc5a9e8697',
		'time': '2010-01-01T01:01:01Z',
		'version': 1633473655066,
		'hasView': True,
		'createdHouston': '2021-10-05T22:40:55.091886+00:00',
		'guid': 'f9aabbd7-56c6-4a68-a097-46fc5a9e8697',
		'submitter': {
			'guid': 'e5435041-b65d-41d7-9a5a-a3168d30ce28',
			'full_name': 'First Middle Last',
			'profile_fileupload': None
		},
		'owner': {
			'guid': 'e5435041-b65d-41d7-9a5a-a3168d30ce28',
			'full_name': 'First Middle Last',
			'profile_fileupload': None
		},
		'hasEdit': True,
		'updatedHouston': '2021-10-05T22:40:55.091905+00:00'
	}],
	'createdEDM': '2021-10-05 22:40:55',
	'customFields': {},
	'locationId': 'test',
	'decimalLongitude': 25.9999,
	'startTime': '2021-10-05T22:40:44.692Z',
	'decimalLatitude': 25.9999,
	'verbatimLocality': 'Saturn',
	'id': 'c3c11028-991c-43aa-be38-45f0dd922415',
	'encounterCounts': {
		'lifeStage': {},
		'sex': {},
		'individuals': 1
	},
	'version': 1633473655066,
	'featuredAssetGuid': None,
	'hasView': True,
	'createdHouston': '2021-10-05T22:40:55.084494+00:00',
	'guid': 'c3c11028-991c-43aa-be38-45f0dd922415',
	'assets': [],
	'hasEdit': True,
	'updatedHouston': '2021-10-05T22:40:55.084518+00:00'
}
```

### CODE REVIEW

**Comment by brmscheiner** [comment]
the encounters are in there twice!

**Comment by colinwkingen** [comment]
Resolution to my earlier problem ended up being adding the "encounters" array to 'dump_only'. It certainly should be read only in this API call. What an unhelpful error message that was, though!

**Comment by colinwkingen** [comment]
> the encounters are in there twice!

@brmscheiner Holy cow, you are right. The EDM and Houston sections are separate. Will fix.

**Comment by colinwkingen** [comment]
@naknomum Is the split between EDM and Houston data why Sighting still has an augment_edm_json method?

**Comment by naknomum** [comment]
> @naknomum Is the split between EDM and Houston data why Sighting still has an augment_edm_json method?
> 
> Or is this a reason to pull EDM data out of the 'result' block?

@colinwkingen  - i think howard and karen [look at this here](https://github.com/WildMeOrg/houston/pull/284#discussion_r699616960), when howard did this augment-to-schema conversion.  basically -- if i am reading it correctly! -- it is because the folding together of edm/houston stuff was more complex than could be handled just by schema.

**Comment by hwindsor** [comment]
> the encounters are in there twice!

The first one is the EDM data for the encounters. The second is the Houston Data for the encounters. 

The question is, do we want to merge them all into one so the frontend doesn't need to know the distinction?

**Comment by colinwkingen** [comment]
> > @naknomum Is the split between EDM and Houston data why Sighting still has an augment_edm_json method?
> > Or is this a reason to pull EDM data out of the 'result' block?
> 
> @colinwkingen - i think howard and karen [look at this here](https://github.com/WildMeOrg/houston/pull/284#discussion_r699616960), when howard did this augment-to-schema conversion. basically -- if i am reading it correctly! -- it is because the folding together of edm/houston stuff was more complex than could be handled just by schema.

Ah, that's what I was afraid of. Will make a wrapper method for Individual.

**Comment by colinwkingen** [comment]
JSON restructured to keep encounter data together and include individual names. @brmscheiner Plz make sure this is how you would like it.

**Pull request closed without merging**
