### PR TITLE
Local deployment of CODEX

### PR DESCRIPTION
**Pull request by mmulich**
## Pull Request Overview

These changes contain the makes of a codex deployment. The scope and intended audience is ourselves (developers) for the purpose of starting up an environment with all the moving parts. 

This is the minimal frame on which we can build from. The hope is that this provides enough foundation for which parallel feature changes can be build from.

Addresses DEX-57

### review

I'd suggest checking out this branch and trying it:
```bash
git checkout codex-deployable
# to ensure you have the version file installed
python3 setup.py --version
# install the frontend
./scripts/build.frontend.sh
# install the swagger-ui
invoke app.dependencies.install-swagger-ui
# build wildme/houston:latest
./scripts/build.docker.sh
cd deploy/codex
docker-compose up
```
Then surf to http://localhost:83/ to see the new site wizard

### development usage

This is currently setup in such a way that the `houston` service can be used as a development environment. That is, the local code is mounted inside the running service. Any updates you make to the code locally will be available the container. However, code reloading is not currently enabled (todo item). Use `docker-compose restart houston` to see the changes reflected in the running instance.

To run commands within the container, use the following command, which will provide you a shell prompt.
```
docker-compose exec houston /bin/bash
```

**Invoke CLI Updates**
New command to initialize the EDM admin user.
This isn't meant to be used directly by the developer. It's primarily meant to be run in the `docker-entrypoint.sh` script during a new startup (without data).

```
$ invoke app.initialize.initialize-edm-admin-user
2021-02-17 23:18:31,043 [INFO] [app] Using app.config 'local_config.LocalConfig'
2021-02-17 23:18:31,697 [INFO] [tasks.app.initialize] Initializing EDM admin user
2021-02-17 23:18:41,458 [INFO] [tasks.app.initialize] Initialized EDM admin user
```

**Pull Request Checklist**
- [X] Ensure that the PR is properly formatted
  - Example: All lint checks are passing
- [X] Ensure that the PR is properly rebased
  - Example: The PR is rebased on `develop` (commit: `<insert develop commit hash>`)
- [X] Ensure that the PR uses a consolidated database migration
  - Example: One database migration is proposed (revision `<insert develop revision>` -> `<insert new revision>`)
- [X] Ensure that the PR is properly tested
  - Example: All automated tests are passing
- [X] Ensure that the PR is properly sanitized
  - Example: No sensitive data or large content was added to this PR
- [x] Ensure that the PR is properly reviewed

### CODE REVIEW

**Review by colinwkingen — COMMENTED** [review]
Following the directions to deploy this, I saw most all moves executed successfully. However, when using `sudo docker-compose up` in the specified directory an error was presented: 

`houston_1  | Traceback (most recent call last):
houston_1  |   File "/usr/local/bin/invoke", line 8, in <module>
houston_1  |     sys.exit(program.run())
houston_1  |   File "/usr/local/lib/python3.7/site-packages/invoke/program.py", line 384, in run
houston_1  |     self.execute()
houston_1  |   File "/usr/local/lib/python3.7/site-packages/invoke/program.py", line 566, in execute
houston_1  |     executor.execute(*self.tasks)
houston_1  |   File "/usr/local/lib/python3.7/site-packages/invoke/executor.py", line 129, in execute
houston_1  |     result = call.task(*args, **call.kwargs)
houston_1  |   File "/usr/local/lib/python3.7/site-packages/invoke/tasks.py", line 127, in __call__
houston_1  |     result = self.body(*args, **kwargs)
houston_1  |   File "/code/tasks/app/_utils.py", line 88, in wrapper
houston_1  |     app = create_app(config_override=config_override)
houston_1  |   File "/code/app/__init__.py", line 144, in create_app
houston_1  |     extensions.init_app(app)
houston_1  |   File "/code/app/extensions/__init__.py", line 276, in init_app
houston_1  |     extension.init_app(app)
houston_1  |   File "/code/app/extensions/tus/__init__.py", line 21, in init_app
houston_1  |     os.makedirs(updir)
houston_1  |   File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
houston_1  |     mkdir(name, mode)
houston_1  | PermissionError: [Errno 13] Permission denied: '_db/uploads'
codex_houston_1 exited with code 1
`
Output after that indicated a successful tomcat/EDM startup but localhost:83 was not visitable.

**Comment by mmulich** [comment]
> ```
> ...
> houston_1  | PermissionError: [Errno 13] Permission denied: '_db/uploads'
> codex_houston_1 exited with code 1
> ```
In the container I change the default location of the database so that it can be within a "volume" (mounted at `/data`) that doesn't get paved over when the development mounts their local code to `/code`.
The `app._ensure_storage` doesn't currently setup this directory `uploads` directory. Looks like it's hardcoded at:
`app/modules/submissions/resources.py:279:            '_db', 'uploads', '-'.join(['sub', str(submission.guid)])`

@colinwkingen, does this error occur while you were trying to use aspects of a site? Or did it occur during the startup?

**Comment by mmulich** [comment]
> Output after that indicated a successful tomcat/EDM startup but localhost:83 was not visitable.

@colinwkingen, was there no connection to the EDM or just a blank page?

**Review by bluemellophone — DISMISSED** [review]
LGTM

**Comment by mmulich** [comment]
@colinwkingen, the error you are experiencing should be fixed in #57.

**Review by colinwkingen — APPROVED** [review]
Approved, and will prioritize #57 also.

**Pull request merged**
