### PR TITLE
Use mkdtemp in site setting test for python3.7

### PR DESCRIPTION
**Pull request by karenc**
When using the `TemporaryDirectory` context manager in python 3.7 and
the directory is not there, it returns an error:

```
            with tempfile.TemporaryDirectory(prefix='trans-', dir=upload_dir) as td:
                transaction_id = Path(td).name[len('trans-') :]

                ...
>               assert resp.json['file_upload_guid'] != str(fup.guid)

tests/modules/site_settings/test_resources.py:85:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.7/tempfile.py:944: in __exit__
    self.cleanup()
/usr/lib/python3.7/tempfile.py:948: in cleanup
    _rmtree(self.name)
/usr/lib/python3.7/shutil.py:482: in rmtree
    onerror(os.lstat, path, sys.exc_info())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path = '/data/var/uploads/trans-o1acga7j', ignore_errors = False
onerror = <function rmtree.<locals>.onerror at 0x7f7104e05598>

    def rmtree(path, ignore_errors=False, onerror=None):
            ...
            try:
>               orig_st = os.lstat(path)
E               FileNotFoundError: [Errno 2] No such file or directory: '/data/var/uploads/trans-o1acga7j'

/usr/lib/python3.7/shutil.py:480: FileNotFoundError
```

To avoid this, just use `mkdtemp` instead which doesn't automatically
clean up.  The transaction directory is should be deleted once it is
processed.

**Pull Request Checklist**
- [x] Ensure that the PR is properly formatted
  - Example: All lint checks are passing
- [x] Ensure that the PR is properly rebased
  - Example: The PR is rebased on `develop` (commit: `<insert develop commit hash>`)
- [x] Ensure that the PR uses a consolidated database migration
  - Example: One database migration is proposed (revision `<insert develop revision>` -> `<insert new revision>`)
- [x] Ensure that the PR is properly tested
  - Example: All automated tests are passing
- [x] Ensure that the PR is properly covered
  - Example: The percentage of the code covered by tests has not decreased
- [x] Ensure that the PR is properly sanitized
  - Example: No sensitive data or large content was added to this PR
- [ ] Ensure that the PR is properly reviewed

### CODE REVIEW

**Comment by karenc** [comment]
I pushed an extra commit just to trigger the nightly tests and they all passed: https://github.com/WildMeOrg/houston/pull/127/commits/bb2cb1c6d4579df9db5ab7760ebc4bba362739ca (I've removed this commit now)

**Comment by colinwkingen** [comment]
Is this similar to the TemporaryDirectoryGraceful replacements that @bluemellophone has in PR #125?

**Comment by bluemellophone** [comment]
Yes, same fix, different path.

**Comment by bluemellophone** [comment]
See here: https://github.com/WildMeOrg/houston/pull/125/files#diff-9e08e8c7769db7b58089fd7659d75ca96df40bb7b5d50299d3a30abd54da9ad6

**Comment by karenc** [comment]
Yeah I only fixed the `tempfile.TemporaryDirectory` that failed while @bluemellophone 's fix can be used for all cases of `TemporaryDirectory` to avoid this error in python 3.7.  I can close this PR

**Pull request closed without merging**
