### PR TITLE
switch to string-based key for EDM config

### PR DESCRIPTION
**Pull request by naknomum**
## Pull Request Overview

Drops integer-based config dicts in favor of string-based keys, as int keys are not compatible with our config when stored as JSON.

**Review Notes**

Basically, you should be able to continue using the existing testing workflow as documented in the README. The changes have been made to be backwards compatible.

I (Michael) wanted to make it back-compat incase we change it again sometime soon. This should keep our workflow intact while still progressing forward.

The `EDM_AUTHENTICATIONS_USERNAME__DEFAULT` & `EDM_AUTHENTICATIONS_PASSWORD__DEFAULT` environment variables must be defined. The defaults for these variables are defined in `.env` (now part of `_db.initial.tar.gz`) and loaded via `config.py`. This replaces the `EDM_AUTHENTICATIONS` value in the `secrets.py` within `_db.initial`.

**Invoke CLI Updates**

New command `app.config.show`, which shows the currently configured settings:

```
$ invoke app.config.show
2021-03-15 07:24:51,200 [INFO] [app] Using app.config 'docker_local_config.LocalConfig'
             Config Key              | Value
------------------------------------------------------------------------------
ENV                                  | production
DEBUG                                | True
TESTING                              | False
PROPAGATE_EXCEPTIONS                 | None
PRESERVE_CONTEXT_ON_EXCEPTION        | None
SECRET_KEY                           | secret
...
```

The `app.dependencies.*` commands have been moved to `dependencies.*` and disassociated with the Flask App object. The intention with this change is to allow these dependency commands to run prior to having a fully configured application.

### CODE REVIEW

**Comment by bluemellophone** [comment]
Note that we will also need to update `_db/secrets.py` and also the stock setup archive `_db.initial.tar.gz`

**Comment by mmulich** [comment]
Note for `deploy/codex/houston/local_config.py`... It's currently using a fixed number for EDM.

FYI my plan on the `local_config` was eventually to do something like:
```
for key in parse_env_keys(prefix='EDM_AUTHENTICATIONS'):
    username = os.getenv(f'EDM_AUTHENTICATIONS_{key}_USERNAME')`
    ...
    config['EDM_AUTHENTICATIONS'][key]['username'] = username
```

**Comment by naknomum** [comment]
last we discussed this, i believe we wanted to go with 'default' (rather than string-'0') to be the default/required key and just skip the whole using numbers thing.  made this tweak now (and rebased to develop).

**Comment by mmulich** [comment]
I'm going to tag myself in on this. ATM I find myself around this code in another branch, so it only makes sense to drop in to wrap this up. 🙌🏼

**Comment by mmulich** [comment]
FYI, I'm not 100% sold on using env-vars in this way. But for the moment it'll work.

Maybe the better thing to do is chuck CSV into a single env-var (e.g. `EDM_AUTHENTICATIONS_CSV`). I'm mostly looking for a solution that can easily be programmatically updated using simple commands (i.e. via bash commands or python stdlib).

I'm also thinking the next step is to possibly collapse the in flask config items for `EDM_URIS` and `EDM_AUTHENTICATIONS` into one `EDM` item.

**Comment by mmulich** [comment]
Ready to roll if you like the changes.

**Review by bluemellophone — APPROVED** [review]
LGTM.

One comment is we need to make a better way to create `_db.initial.tar.gz`.  Ideally we could use a `mako` template similar to how the migration files are generated.  The only real thing we need that file for is `_db/secrets.py` since we have the initialization and _reset scripts now.

**Comment by mmulich** [comment]
I fixed a missed usage in `task/app/initialization.py` and lumped it in with the major change to using the `'default'` key. I also fixed an invocation in `docker-entrypoint.sh` that broke in the move of the `dependencies.install` task.
I haven't been able to find anything else wrong during my testing and usage of these changes in another dependent branch.

**Pull request merged**
