### PR TITLE
894 Remove gumby indexes and proxy search endpoints

### PR DESCRIPTION
**Pull request by mmulich**
## Pull Request Overview

- [Fix initial and error values for elasticsearch test check](https://github.com/WildMeOrg/houston/commit/11038928389c60a0b50458b42c63df5158e6ef0a) - @bluemellophone, I may have changed your intention with this change, so just review it for accuracy.
- [Removes gumby managed indexes](https://github.com/WildMeOrg/houston/commit/373c751b9b6a7ba163fc4340e752857b283f192d)

    This change removes the gumby managed indexes that are no longer used by the frontend.

    The primary focus of this changeset has been to remove the unnecessary indexing of individuals, encounters and sightings. The secondary, but important to other work, focus is to remove the need for the
`postgres_fdw` extension within the EDM database. This removal of the indexing code will remove the need for those foreign table definitions.

    This does not remove gumby itself. That will come in a later changeset

**REST API Updates**

- removes `/api/v1/search/proxy/<index>`

### CODE REVIEW

**Comment by mmulich** [comment]
Note, this changeset is not intended to fully address DEX-894. It's a partial resolution, in that it does not remove gumby. I'm more concerned with the removal of the postgres `postgres_fdw` extension, which is currently blocking the production deployment of the zebra migration dataset.

**Review by hwindsor — COMMENTED** [review]
LGTM but as JP wrote all this, I'll leave him to approve.

**Review by bluemellophone — APPROVED** [review]
LGTM, the status to `{}` change is fine

**Comment by bluemellophone** [comment]
@mmulich Does this PR remove all imports / requirements / installing of Gumby?

**Pull request merged**
