### PR TITLE
728 indiv names on sighting encounters

### PR DESCRIPTION
**Pull request by drewblount**
Moves some schemas (schemae?) around so that individual names are included on a sighting's encounters, with each name's context and value listed.

Adds a NamedIndividualSchema to individuals/schemas.py which is just the base schema plus names. This is then included in the encounter AugmentedEdmSchema which is used on a sighting GET.

`test_create_sighting.py::test_edm_and_houston_encounter_data_within_sightings` tests that we're getting the contexts and values for each name.

A side-effect here you'll see in the integration test is that if there is no individual on an encounter, that entry will be `individual: None` on the sighting encounter, conforming with other None-able fields like submitter. Previously, the no-individual value was `{}`.

### CODE REVIEW

**Comment by drewblount** [comment]
leaving this as a draft until tests are complete since I just rebased.

**Comment by drewblount** [comment]
\rebase

**Review by naknomum — APPROVED** [review]
lgtm

**Pull request merged**
