### PR TITLE
Allow Gumby tasks to be invoked from Houston code space

### PR DESCRIPTION
**Pull request by mmulich**
## Pull Request Overview

Allow Gumby tasks to be invoked from Houston code space

---

**Invoke CLI Updates**

This adds the `gumby` library defined invoke task to Houston under the gumby namespace: `invoke gumby.<task>`.

For example:
```
$ invoke gumby.init
$ invoke gumby.load-random-data
```

### CODE REVIEW

**Comment by mmulich** [comment]
Note, you will need to rebuild the houston image to make this work: `docker compose build && docker compose up -d`

☝🏼 This is due to pip being able to check for updates to git repository installed code. Or at least that's what it looked like when I tried things.

**Review by brmscheiner — COMMENTED** [review]
For me houston is throwing an error that prevents the server from coming up:

```
houston_1  | WARNING: '.' not a valid package name; please use only .-separated package names in setup.py
houston_1  | /usr/local/lib/python3.9/site-packages/setuptools/dist.py:483: UserWarning: The version specified ('0.1.0.e4302153') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
houston_1  |   warnings.warn(
houston_1  | 0.1.0.e4302153
houston_1  | Traceback (most recent call last):
houston_1  |   File "/usr/local/bin/invoke", line 8, in <module>
houston_1  | Creating AssetGroup path: '/data/var/asset_group'
houston_1  |     sys.exit(program.run())
houston_1  |   File "/usr/local/lib/python3.9/site-packages/invoke/program.py", line 373, in run
houston_1  |     self.parse_collection()
houston_1  |   File "/usr/local/lib/python3.9/site-packages/invoke/program.py", line 465, in parse_collection
houston_1  |     self.load_collection()
houston_1  |   File "/usr/local/lib/python3.9/site-packages/invoke/program.py", line 696, in load_collection
houston_1  |     module, parent = loader.load(coll_name)
houston_1  |   File "/usr/local/lib/python3.9/site-packages/invoke/loader.py", line 76, in load
houston_1  |     module = imp.load_module(name, fd, path, desc)
houston_1  |   File "/usr/local/lib/python3.9/imp.py", line 244, in load_module
houston_1  |     return load_package(name, filename)
houston_1  |   File "/usr/local/lib/python3.9/imp.py", line 216, in load_package
houston_1  |     return _load(spec)
houston_1  |   File "<frozen importlib._bootstrap>", line 711, in _load
houston_1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
houston_1  |   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
houston_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
houston_1  |   File "/code/tasks/__init__.py", line 62, in <module>
houston_1  |     from tasks import app as tasks_app  # NOQA
houston_1  |   File "/code/tasks/app/__init__.py", line 8, in <module>
houston_1  |     from tasks.app import (
houston_1  |   File "/code/tasks/app/consistency.py", line 11, in <module>
houston_1  |     from app.extensions import db
houston_1  |   File "/code/app/__init__.py", line 177, in <module>
houston_1  |     _ensure_storage()
houston_1  |   File "/code/app/__init__.py", line 48, in _ensure_storage
houston_1  |     os.mkdir(path)
houston_1  | OSError: [Errno 28] No space left on device: '/data/var/asset_group'
```

I did `docker build` before bringing the containers up, also tried big red button with the same result

**Comment by colinwkingen** [comment]
@brmscheiner From the `No space left on device`, is there plenty of space on your machine? I'm not sure if there is some docker volume space limiting thing we could have somehow exceeded.

**Review by brmscheiner — APPROVED** [review]
Thanks @colinwkingen. Cleared up my dockerspace and now it's working. I can see individuals!

**Pull request merged**
