### PR TITLE
DEX-279 Rename AssetGroupManager to Gitlab

### PR DESCRIPTION
**Pull request by karenc**
## Pull Request Overview

- Revert "Implement local alternative to gitlab"

  This reverts commit 4171f55d56583cd2dec146f7d3b7b7226fac8c83.

- Change houston gitlab set up script to skip if gitlab not available

  We are making gitlab optional so if `GITLAB_REMOTE_URI` is not set, the
  gitlab set up script should skip.

- Rename app/extensions/asset_group to app/extensions/gitlab.py

  I think it will be clearer what this extension actually is if we call it
  gitlab.

- Rename AssetGroupManager to GitlabManager

  This should make it pretty clear when we are using gitlab.

---

**Review Notes**
- What do people think about renaming `AssetGroupManager` to `Gitlab`?  I wanted to make it clearer what the extension is actually for.

This is only part 1 of DEX-279 make gitlab optional and only sync if available.

### CODE REVIEW

**Comment by colinwkingen** [comment]
I'm a little torn. I see the value in making it clear when Gitlab is being used, but am a little hesitant to lock us into Gitlab technology by embedding it's name into one of our classes. Definitely want @naknomum and @hwindsor input on the renaming.

**Comment by hwindsor** [comment]
There's two aspects to this.
Firstly the current AssetGroupManager is very much not AssetGroup specific and is very Gitlab specific so that change does make sense.
Secondly, to my mind there is far too much git specific logic and gitlab specific stuff in the asset_group model code and we should try to move it out. 
The problem is that if we have github/gitlab/local git as options and there is a separate extension for each, the calling code must know exactly which to call. From the changes made throughout the code, this would be quite significant.
Which git implementation is used needs to be abstracted so that the rest of the system does not need to know.
How about making it current_app.git instead of current_app.gitlab. Then in the init_app function it would set current_app.git and at that point could choose which implementation to configure current_app.git to be.
I'm thinking that there could be a common base class with options of derived classes for each backend. 
Then the calling code would call the current_app.git methods without needing to know the implementation used. 
The way I look at it is that this block is providing persistent storage of the data we have in asset_groups and at the moment gitlab is the tool that is used to provide it. We really must avoid hard baking that into the rest of he codebase.

**Comment by karenc** [comment]
@colinwkingen I'm currently still working on the code but at the moment, these are the methods in `app/extensions/gitlab.py`:

```
app/extensions/gitlab.py:    def __init__(self, pre_initialize=False, *args, **kwargs):
app/extensions/gitlab.py:    def _gitlab_group(self):
app/extensions/gitlab.py:    def _get_gitlab_project(self, name):
app/extensions/gitlab.py:    def _ensure_initialized(self):
app/extensions/gitlab.py:    def _ensure_project(self, asset_group, additional_tags=[]):
app/extensions/gitlab.py:    def _ensure_repository_files(self, group_path, project):
app/extensions/gitlab.py:    def ensure_repository(self, asset_group):
app/extensions/gitlab.py:    def create_repository(self, asset_group, additional_tags=[]):
app/extensions/gitlab.py:    def get_repository(self, asset_group):
app/extensions/gitlab.py:    def assert_taglist(self, asset_group_uuid, whitelist_tag):
app/extensions/gitlab.py:    def is_asset_group_on_remote(self, asset_group_uuid):
app/extensions/gitlab.py:    def delete_remote_asset_group(self, asset_group):
app/extensions/gitlab.py:    def delete_remote_project(self, project):
```

We can replace `asset_group` with `repository_name` and it would basically be a generic gitlab package.

---

@hwindsor I'm planning to change any calls to `current_app.gitlab` so everything happens in the `AssetGroup` model to limit the knowledge of gitlab outside of `AssetGroup`.  I think calling it `current_app.gitlab` is appropriate personally, and renaming it later should we change from gitlab to something else should be very quick.  On the other hand it's also not a big problem to not call it `gitlab` ...

**Comment by hwindsor** [comment]
As discussed, I think current_app.git_backend is a better name as then if you were to change to github, it would be a one line change. 
that describes clearly what it is doing (backing up the git repos) while abstracting how it is doing so

**Comment by karenc** [comment]
@hwindsor I changed `current_app.gitlab` to `current_app.git_backend` and squashed it into the last commit.  I also added part of the discussion into the commit message

**Review by hwindsor — APPROVED** [review]
I like the direction of travel. This area needs sorting out.

**Comment by colinwkingen** [comment]
@karenc Looks like some bumps against Howards last PR. I'm ready to merge when resolved.

**Comment by colinwkingen** [comment]
Ha! You beat me to it by 1 second exactly

**Comment by karenc** [comment]
I think you beat me to it 🤣

**Pull request merged**
