### PR TITLE
DEX-645 back end add time and timeSpecificity parameters to ags patch…

### PR DESCRIPTION
**Pull request by Atticus29**
## Pull Request Overview

- Added time and timeSpecificity as params to the asset group sighting PATCH api
- Followed JVO's exact instructions lol

---

**Review Notes**
- Previously, a patch request resulted in a 402 error with "no valid choice" for the specified time and timeSpecificity paths.
- I don't _think_ any db table modifications are needed, but I have absolutely no idea.

### CODE REVIEW

**Comment by Atticus29** [comment]
@naknomum let me know whether I still need to do any rebasing or anything.

**Review by colinwkingen — APPROVED** [review]
LGTM

**Comment by colinwkingen** [comment]
Looks like it did need a rebase, which can be done in a comment such as the above. Tests rolling now.

**Pull request merged**
