### PR TITLE
686 add annotations to encounter data in sighting and AGSget response

### PR DESCRIPTION
**Pull request by hwindsor**
## Pull Request Overview

- Added annotations to the encounters data within AGS and Sightiong get response
- 

---

**REST API Updates **

A new example POST API is defined with its expected parameters, if needed to be specified for a thorough review

```
[GET] /api/v1/asset-group_sighting/as_sighting/{guid}
{
    "asset_group_guid": "d8b16ba7-7785-4500-8f71-b1dbde709929",
    "assets": [
        {
            "annotations": [
                {
                    "asset_guid": "8e8e9480-0092-40a9-8c31-6bf42fed2648",
                    "bounds": {
                        "rect": [
                            459,
                            126,
                            531,
                            539
                        ],
                        "theta": 0.0
                    },
                    "created": "2022-01-21T17:32:36.493693+00:00",
                    "encounter_guid": null,
                    "guid": "a086c77a-6662-43a4-b625-b1dbeac56afe",
                    "ia_class": "zebra_plains",
                    "keywords": [],
                    "updated": "2022-01-21T17:32:36.493709+00:00",
                    "viewpoint": "test"
                },
                {
                    "asset_guid": "8e8e9480-0092-40a9-8c31-6bf42fed2648",
                    "bounds": {
                        "rect": [
                            26,
                            145,
                            471,
                            500
                        ],
                        "theta": 0.0
                    },
                    "created": "2022-01-21T17:32:36.493923+00:00",
                    "encounter_guid": null,
                    "guid": "f764442a-4c5e-48ac-a1ab-fc1660686b1d",
                    "ia_class": "zebra_plains",
                    "keywords": [],
                    "updated": "2022-01-21T17:32:36.493929+00:00",
                    "viewpoint": "test"
                }
            ],
            "created": "2022-01-21T17:32:36.012583+00:00",
            "dimensions": {
                "height": 664,
                "width": 1000
            },
            "filename": "zebra.jpg",
            "guid": "8e8e9480-0092-40a9-8c31-6bf42fed2648",
            "src": "/api/v1/assets/src/8e8e9480-0092-40a9-8c31-6bf42fed2648",
            "updated": "2022-01-21T17:32:36.012591+00:00"
        },
        {
            "annotations": [],
            "created": "2022-01-21T17:32:36.004529+00:00",
            "dimensions": {
                "height": 578,
                "width": 963
            },
            "filename": "coelacanth.png",
            "guid": "a95d4dec-6324-48ce-8c59-daa6294dd933",
            "src": "/api/v1/assets/src/a95d4dec-6324-48ce-8c59-daa6294dd933",
            "updated": "2022-01-21T17:32:36.004549+00:00"
        }
    ],
    "comments": null,
    "completion": 10,
    "created": "2022-01-21T17:32:36.236139+00:00",
    "createdEDM": null,
    "createdHouston": "2022-01-21T17:32:36.236139+00:00",
    "creator": {
        "full_name": "First Middle Last",
        "guid": "3ce00d24-36c0-48ce-ba16-18dc7c41399a",
        "profile_fileupload": null
    },
    "curation_start_time": "2022-01-21T17:32:36.512558Z",
    "customFields": {},
    "decimalLatitude": null,
    "decimalLongitude": null,
    "detection_start_time": "2022-01-21T17:32:36.236139Z",
    "encounterCounts": {},
    "encounters": [
        {
            "annotations": [
                {
                    "asset_guid": "8e8e9480-0092-40a9-8c31-6bf42fed2648",
                    "encounter_guid": "d5279f55-77b7-4b7a-ac34-cbaeb8892b6f",
                    "guid": "a086c77a-6662-43a4-b625-b1dbeac56afe",
                    "ia_class": "zebra_plains",
                    "viewpoint": "test"
                },
                {
                    "asset_guid": "8e8e9480-0092-40a9-8c31-6bf42fed2648",
                    "encounter_guid": "d5279f55-77b7-4b7a-ac34-cbaeb8892b6f",
                    "guid": "f764442a-4c5e-48ac-a1ab-fc1660686b1d",
                    "ia_class": "zebra_plains",
                    "viewpoint": "test"
                }
            ],
            "createdHouston": "2022-01-21T17:32:36.236139+00:00",
            "customFields": {},
            "decimalLatitude": null,
            "decimalLongitude": null,
            "guid": "d5279f55-77b7-4b7a-ac34-cbaeb8892b6f",
            "hasEdit": true,
            "hasView": true,
            "individual": {},
            "owner": {
                "full_name": "First Middle Last",
                "guid": "3ce00d24-36c0-48ce-ba16-18dc7c41399a",
                "profile_fileupload": null
            },
            "sex": null,
            "submitter": null,
            "time": null,
            "timeSpecificity": null,
            "updatedHouston": "2022-01-21T17:32:36.236153+00:00",
            "version": null
        },
        {
            "createdHouston": "2022-01-21T17:32:36.236139+00:00",
            "customFields": {},
            "decimalLatitude": null,
            "decimalLongitude": null,
            "guid": "03751242-cc77-4563-b6f3-522c2f39be79",
            "hasEdit": true,
            "hasView": true,
            "individual": {},
            "owner": {
                "full_name": "First Middle Last",
                "guid": "3ce00d24-36c0-48ce-ba16-18dc7c41399a",
                "profile_fileupload": null
            },
            "sex": null,
            "submitter": null,
            "time": null,
            "timeSpecificity": null,
            "updatedHouston": "2022-01-21T17:32:36.236153+00:00",
            "version": null
        }
    ],
    "featuredAssetGuid": null,
    "guid": "4b5196be-800c-4148-9cb4-7287a5690899",
    "hasEdit": true,
    "hasView": true,
    "identification_start_time": null,
    "locationId": "Tiddleywink",
    "review_time": null,
    "sightingGuid": null,
    "speciesDetectionModel": [
        "african_terrestrial"
    ],
    "stage": "curation",
    "time": "2000-01-01T01:01:01+00:00",
    "timeSpecificity": "time",
    "unreviewed_start_time": null,
    "updated": "2022-01-21T17:32:36.236153+00:00",
    "updatedHouston": "2022-01-21T17:32:36.236153+00:00",
    "verbatimEventDate": "",
    "verbatimLocality": "",
    "version": null
}

[GET] /api/v1/sighting/{guid}
{
    "assets": [
        {
            "annotations": [
                {
                    "asset_guid": "8e8e9480-0092-40a9-8c31-6bf42fed2648",
                    "encounter_guid": "b8efdf3c-706a-4360-a104-741cd9244146",
                    "guid": "a086c77a-6662-43a4-b625-b1dbeac56afe",
                    "ia_class": "zebra_plains",
                    "viewpoint": "test"
                },
                {
                    "asset_guid": "8e8e9480-0092-40a9-8c31-6bf42fed2648",
                    "encounter_guid": "b8efdf3c-706a-4360-a104-741cd9244146",
                    "guid": "f764442a-4c5e-48ac-a1ab-fc1660686b1d",
                    "ia_class": "zebra_plains",
                    "viewpoint": "test"
                }
            ],
            "created": "2022-01-21T17:32:36.012583+00:00",
            "dimensions": {
                "height": 664,
                "width": 1000
            },
            "filename": "zebra.jpg",
            "guid": "8e8e9480-0092-40a9-8c31-6bf42fed2648",
            "src": "/api/v1/assets/src/8e8e9480-0092-40a9-8c31-6bf42fed2648",
            "updated": "2022-01-21T17:32:36.012591+00:00"
        },
        {
            "annotations": [],
            "created": "2022-01-21T17:32:36.004529+00:00",
            "dimensions": {
                "height": 578,
                "width": 963
            },
            "filename": "coelacanth.png",
            "guid": "a95d4dec-6324-48ce-8c59-daa6294dd933",
            "src": "/api/v1/assets/src/a95d4dec-6324-48ce-8c59-daa6294dd933",
            "updated": "2022-01-21T17:32:36.004549+00:00"
        }
    ],
    "comments": "None",
    "created": "2022-01-21T17:33:13.773667+00:00",
    "createdEDM": "2022-01-21 17:33:13",
    "createdHouston": "2022-01-21T17:33:13.773667+00:00",
    "creator": {
        "full_name": "First Middle Last",
        "guid": "3ce00d24-36c0-48ce-ba16-18dc7c41399a",
        "profile_fileupload": null
    },
    "curation_start_time": "2022-01-21T17:32:36.512558Z",
    "customFields": {},
    "detection_start_time": "2022-01-21T17:32:36.236139Z",
    "encounterCounts": {
        "individuals": 0,
        "sex": {}
    },
    "encounters": [
        {
            "annotations": [
                {
                    "asset_guid": "8e8e9480-0092-40a9-8c31-6bf42fed2648",
                    "encounter_guid": "b8efdf3c-706a-4360-a104-741cd9244146",
                    "guid": "a086c77a-6662-43a4-b625-b1dbeac56afe",
                    "ia_class": "zebra_plains",
                    "viewpoint": "test"
                },
                {
                    "asset_guid": "8e8e9480-0092-40a9-8c31-6bf42fed2648",
                    "encounter_guid": "b8efdf3c-706a-4360-a104-741cd9244146",
                    "guid": "f764442a-4c5e-48ac-a1ab-fc1660686b1d",
                    "ia_class": "zebra_plains",
                    "viewpoint": "test"
                }
            ],
            "created": "2022-01-21T17:33:13.962686+00:00",
            "createdHouston": "2022-01-21T17:33:13.962686+00:00",
            "guid": "b8efdf3c-706a-4360-a104-741cd9244146",
            "hasEdit": true,
            "hasView": true,
            "owner": {
                "full_name": "First Middle Last",
                "guid": "3ce00d24-36c0-48ce-ba16-18dc7c41399a",
                "profile_fileupload": null
            },
            "owner_guid": "3ce00d24-36c0-48ce-ba16-18dc7c41399a",
            "public": false,
            "submitter": null,
            "time": null,
            "timeSpecificity": null,
            "updated": "2022-01-21T17:33:13.962697+00:00",
            "updatedHouston": "2022-01-21T17:33:13.962697+00:00"
        },
        {
            "annotations": [],
            "created": "2022-01-21T17:33:14.012545+00:00",
            "createdHouston": "2022-01-21T17:33:14.012545+00:00",
            "guid": "c8b97249-9a6d-4c26-977b-77c4797a5c71",
            "hasEdit": true,
            "hasView": true,
            "owner": {
                "full_name": "First Middle Last",
                "guid": "3ce00d24-36c0-48ce-ba16-18dc7c41399a",
                "profile_fileupload": null
            },
            "owner_guid": "3ce00d24-36c0-48ce-ba16-18dc7c41399a",
            "public": false,
            "submitter": null,
            "time": null,
            "timeSpecificity": null,
            "updated": "2022-01-21T17:33:14.012555+00:00",
            "updatedHouston": "2022-01-21T17:33:14.012555+00:00"
        }
    ],
    "featuredAssetGuid": "8e8e9480-0092-40a9-8c31-6bf42fed2648",
    "guid": "154ddf2f-6a94-4662-858f-7165e3fb949d",
    "hasEdit": true,
    "hasView": true,
    "identification_start_time": null,
    "locationId": "Tiddleywink",
    "review_time": null,
    "speciesDetectionModel": [
        "african_terrestrial"
    ],
    "stage": "un_reviewed",
    "time": "2000-01-01T01:01:01+00:00",
    "timeSpecificity": "time",
    "unreviewed_start_time": "2022-01-21T17:33:13.773736Z",
    "updated": "2022-01-21T17:33:13.773685+00:00",
    "updatedHouston": "2022-01-21T17:33:13.773685+00:00",
    "version": 1642786393752
}
```

### CODE REVIEW

**Review by colinwkingen — APPROVED** [review]
LGTM

**Comment by colinwkingen** [comment]
Ready to merge when @brmscheiner approves on a non-MWS day.

**Review by brmscheiner — APPROVED** [review]

**Pull request merged**
