### PR TITLE
Organized documentation for better maintainability

### PR DESCRIPTION
**Pull request by mmulich**
## Pull Request Overview

This is a quick attempt to:
1. simplify the readme so that it gets just enough information into the user's hands without being overwhelming
1. keep the documentation as close to the implementation as possible
1. organize the documentation into maintainable chunks that can both be found and manipulated by the developers
1. produce the foundation for producing higher quality documentation (including auto-documenting from docs in the code)

I realize it's a bit sloppy, but the goal wasn't to make it perfect. It's a starting point where everything can hop into improving.

I have made the decision to allow both restructuredtext (rst) and markdown (md). Part of that was because I didn't want to translate the existing md to rst. The other reason is because for lots of developers, md is easier to grok and make quick changes. On the other hand, rst still provides power for those that need it; and `recommonmark` allows the use of embedded rst in markdown, which means we can still use the power of sphinx extensions.

---

**Review Notes**

You can see the prerendered results of this by surfing around the branch on github: https://github.com/WildMeOrg/houston/tree/organized-docs

If you would like to see the built docs, try the [Build the documentation](https://github.com/WildMeOrg/houston/tree/organized-docs#build-the-documentation) instructions within the README.

If you spot typos or grammatical issues, feel free to commit fixes.

I did talk with Ben about this in relation to docs.wildme.org. He's cool with this approach to things and linking from within docs.wildme.org to the built docs (once an automated build is happening).

---

Note, a future PR will automate the build and deploy of these docs. I'm just getting this portion of things committed for now. Thanks!

**Pull Request Checklist**
- [X] Ensure that the PR is properly formatted
  - Example: All lint checks are passing
- [X] Ensure that the PR is properly rebased
  - Example: The PR is rebased on `develop` (commit: `<insert develop commit hash>`)
- [X] Ensure that the PR uses a consolidated database migration
  - Example: One database migration is proposed (revision `<insert develop revision>` -> `<insert new revision>`)
- [X] Ensure that the PR is properly tested
  - Example: All automated tests are passing
- [X] Ensure that the PR is properly covered
  - Example: The percentage of the code covered by tests has not decreased
- [X] Ensure that the PR is properly sanitized
  - Example: No sensitive data or large content was added to this PR
- [ ] Ensure that the PR is properly reviewed

### CODE REVIEW

**Comment by mmulich** [comment]
To give you an idea of what the frontpage of the rendered documentation looks like without building the docs yourself:

Screen Shot 2021-03-18 at 18 28 58

**Comment by naknomum** [comment]
this is a great effort... i am just starting to browse through it all but it seems like a great breakdown of all the moving pieces.   glad you are bouncing ideas off ben too, re: docs.wildme ... it may be a little clunky to flip between the two, but i think its the best solution for taking advantage of both documentation realms.  thanks!

**Review by colinwkingen — APPROVED** [review]
LGTM, thanks for doing this.

**Pull request merged**
