### PR TITLE
Upgrade houston dockerfile to python:3.9

### PR DESCRIPTION
**Pull request by karenc**
## Pull Request Overview

- Upgrade houston Dockerfile from python:3.7 to python:3.9
- Only upload coverage to codecov for ubuntu py3.9
- Update codecov action to 1.2.1 in testing workflow

**Pull Request Checklist**
- [x] Ensure that the PR is properly formatted
  - Example: All lint checks are passing
- [x] Ensure that the PR is properly rebased
  - Example: The PR is rebased on `develop` (commit: `<insert develop commit hash>`)
- [x] Ensure that the PR uses a consolidated database migration
  - Example: One database migration is proposed (revision `<insert develop revision>` -> `<insert new revision>`)
- [x] Ensure that the PR is properly tested
  - Example: All automated tests are passing
- [x] Ensure that the PR is properly sanitized
  - Example: No sensitive data or large content was added to this PR
- [x] Ensure that the PR is properly reviewed

### CODE REVIEW

**Comment by karenc** [comment]
@colinwkingen Sorry I changed the testing workflow job names (added "sqlite://") again...  If this PR is accepted, we'll need to change the required checks again at https://github.com/WildMeOrg/houston/settings/branches

**Review by colinwkingen — DISMISSED** [review]
LGTM, I'll look at updating the testing job names.

**Review by mmulich — APPROVED** [review]

**Review by colinwkingen — APPROVED** [review]
LGTM

**Comment by mmulich** [comment]
Ah, the required checks need updated again: Settings > Branches > "Require status checks to pass before merging"

**Comment by bluemellophone** [comment]
> Ah, the required checks need updated again: Settings > Branches > "Require status checks to pass before merging"

Fixed

**Pull request merged**
