### PR TITLE
DEX-359 Add roles and profile image to users listing api

### PR DESCRIPTION
**Pull request by karenc**
The API now returns something like this:

```
[
    {
        "is_internal": true,
        "is_exporter": false,
        "is_active": true,
        "profile_fileupload": {
            "created": "2021-07-09T20:20:31.888901+00:00",
            "mime_type": "image/png",
            "guid": "ec220d3a-36c4-43a2-a062-3343eeb025bc",
            "src": "/api/v1/fileuploads/src/ec220d3a-36c4-43a2-a062-3343eeb025bc",
            "updated": "2021-07-09T20:20:31.888927+00:00"
        },
        "in_alpha": false,
        "is_admin": true,
        "is_user_manager": false,
        "is_staff": false,
        "guid": "366cb80a-e971-4576-b851-8c75177d1d6a",
        "is_researcher": false,
        "full_name": "",
        "in_beta": false,
        "is_contributor": true,
        "email": "root@example.org"
    },
    ...
```

### CODE REVIEW

**Review by brmscheiner — APPROVED** [review]
Works for me!

**Comment by karenc** [comment]
There's some (probably) unrelated test failures I need to fix

**Comment by karenc** [comment]
Test fixed in #241

**Comment by naknomum** [comment]
code all looks good to me, but wanted to confirm:  is this listing (and this level-of-detail) only something *admin*-like folks can see?  just curious cuz wondering if any-old-user can see this, if that might be leaking too much info.  (e.g. who has what roles)

**Comment by karenc** [comment]
> code all looks good to me, but wanted to confirm: is this listing (and this level-of-detail) only something _admin_-like folks can see? just curious cuz wondering if any-old-user can see this, if that might be leaking too much info. (e.g. who has what roles)

@naknomum I think that makes sense.  It's definitely possible to change schema according to permission, I think I've seen it somewhere...

**Comment by colinwkingen** [comment]
Lets roll with it for now. It can be added to the admin user list page, and then when we need it somewhere less secure we can discuss what should be omitted in another schema.

**Comment by karenc** [comment]
Oh yeah I forgot the API is already protected so this is ok :+1:

**Pull request merged**
