### PR TITLE
DEX-539 DEX-541 Add recaptcha to POST /api/v1/asset_groups/

### PR DESCRIPTION
**Pull request by karenc**
- Add a `@recaptcha_required` decorator for resource functions
- Validate the `token` in `request.data` with recaptcha and returns 400
  Bad Request if bot score fails

### CODE REVIEW

**Review by bluemellophone — APPROVED** [review]
LGTM, should we add captchas on creating new user accounts?

**Comment by karenc** [comment]
> LGTM, should we add captchas on creating new user accounts?

@bluemellophone Yeah we can really add it to any APIs.  The version I implemented is recaptcha v3 and that's invisible.  There's not even a checkbox, so we can do it without interrupting the user.  Is recaptcha v3 ok?

**Comment by karenc** [comment]
@bluemellophone It looks like there's no sign up page at the moment, should we add recaptcha to "request an invitation"?

**Comment by bluemellophone** [comment]
I think this is a product question for Tanya, but reinforced by scriptable security vectors that result in CREATE operations.  Let's bring it up during the Friday meeting tomorrow and see if we need to make a ticket.

**Pull request merged**
