### PR TITLE
1028 merge individual notification messages

### PR DESCRIPTION
**Pull request by hwindsor**
## Pull Request Overview

- Format of notification messages changed as discussed
- Merge declied separated out from merge complete notification as requested

```
 [{'created': '2022-05-17T18:30:40.558013+00:00',
    'elasticsearchable': True,
    'guid': '051cb5f1-7850-44af-8459-d0a84a888062',
    'indexed': '2022-05-17T18:30:40.557981+00:00',
    'is_read': False,
    'is_resolved': False,
    'message_type': 'individual_merge_request',
    'message_values': {'other_individuals': [{'guid': '29aac154-7eae-406c-89e3-7eecdc644899',
                                            'primaryName': 'Hannibal'}],
                     'request_id': 'e9e80ad6-5e72-457b-b389-e2d85193e76d',
                     'source_names_list': '',
                     'target_individual_guid': 'b9f79a30-ad6e-4e6b-a120-4430e09858d4',
                     'target_individual_name': 'Archibald',
                     'your_individuals': [{'guid': 'b9f79a30-ad6e-4e6b-a120-4430e09858d4',
                                           'primaryName': 'Archibald'}]},
  'sender_guid': '8efc391f-7499-4a0b-b647-d6309e85687a',
  'sender_name': 'First Middle Last'}]
```

### CODE REVIEW

**Comment by naknomum** [comment]
looks good!  only suggestion i would have is to at least stub out a rough approximation of `app/templates/email/en_us/notifications/individual_merge_declined*` files to go along with new notification type.

**Review by naknomum — APPROVED** [review]
LGTM

**Comment by Atticus29** [comment]
I'm ok with this! Thank you!

**Review by Atticus29 — APPROVED** [review]

**Comment by hwindsor** [comment]
> looks good! only suggestion i would have is to at least stub out a rough approximation of `app/templates/email/en_us/notifications/individual_merge_declined*` files to go along with new notification type.

Yes, I remembered afterwards that I'd missed those. Thanks for the feedback. I wanted to get approval for the general direction of travel first.

**Review by drewblount — APPROVED** [review]
LGTM. Let's merge this before PR 927, which I will rebase over this after it is merge.

**Pull request merged**
