### PR TITLE
Configurable frontend build locations

### PR DESCRIPTION
**Pull request by mmulich**
### First part that was previously part of #133 

- (Continuation of #125)
- Fixes the frontend build (mostly by updating the submodule ref)
- Frontend build script now gives useful remediation steps on error
- Fixes the build scripts so that they may be sourced (e.g. source ./scripts/build.frontend.sh && build)
- Builds the frontend & swagger-ui into the image (note, followup changes will improve upon this)

### Second half that focuses on configurability

- Enables the ops user to configure where the built frontends are located on the filesystem. In the container setting, this enables the developer to mount over the backend code without removing the pre-built frontends.
- Removes `/api/v1/frontends` in favor of whatever will come out of DEX-273. The endpoint is currently unused by the frontend.
- Removal of the frontend version from the Houston UI. This was done, because there is no guarantee that Houston has the frontend installed.
- Reorganizes the frontend module into frontend_ui, app_ui and swagger_ui; and moves the auth functions into the auth module.

---

**Review Notes**

The primary purpose of this PR is to be able to configure the location of the built frontends.

This now brings the docker setup instructions to `docker-compose up`, because the frontends are now in the image and won't get paved over when the houston code is mounted over the images' code.

**Pull Request Checklist**
- [x] Ensure that the PR is properly formatted
  - Example: All lint checks are passing
- [x] Ensure that the PR is properly rebased
  - Example: The PR is rebased on `develop` (commit: `<insert develop commit hash>`)
- [x] Ensure that the PR uses a consolidated database migration
  - Example: One database migration is proposed (revision `<insert develop revision>` -> `<insert new revision>`)
- [x] Ensure that the PR is properly tested
  - Example: All automated tests are passing
- [x] Ensure that the PR is properly covered
  - Example: The percentage of the code covered by tests has not decreased
- [x] Ensure that the PR is properly sanitized
  - Example: No sensitive data or large content was added to this PR

### CODE REVIEW

**Comment by mmulich** [comment]
This is ready. It just depends on #133

**Comment by mmulich** [comment]
@brmscheiner this is what we ran on your machine. Please ✅ when you have a moment.

@colinwkingen, this worked for Ben. I saw it with my own 👀 while we screen shared to debug any issues.

So this PR is a bit large now, but that's the nature of things. 🤷🏼 Seemed easier to just lump everything together rather than create two separate PRs again.

**Review by brmscheiner — APPROVED** [review]

**Comment by colinwkingen** [comment]
Just to confirm, parts of this PR were previously in #133 but this still depends on #133 being merged first?

**Comment by mmulich** [comment]
It includes #133

**Pull request merged**
